version: '3.7'

services:

  subscribers:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - API_KEY=K8p68cOIgB761GJZCeKnZpf+gCbrPAfy5WPjET1VHAEXO9gB42mfKsCVUZPdFGXzIAME+OTnaupBaM68okSS58pRKLGsoRhl3lZyO2WzaNifqGqMQJkSun58a+QDQfPMwvICdAoD5nAmpFMayn5j2A==
      - DATABASE_URL=postgresql://postgres:postgres@subscribers-db:5432/subscribers_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@subscribers-db:5432/subscribers_test
    depends_on:
      - subscribers-db

  subscribers-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres